### ISSUE TITLE
Why is "HiLink stanCppConflict Error"?

### ISSUE THREAD

**Issue by JohnReid** [maverickg/stan.vim#3]
Why is `stanCppConflict` shown as an `Error` (assuming I'm interpreting stan.vim correctly)? I think this makes `void` and `return` appear as red in my vim which is a little distracting. Many thanks for the plugin BTW.

**Comment by maverickg** [comment]
This is not fully updated for the recent version of stan.  Previously, when stan didn't support user defined functions, void and return should not appear in the code.

**Comment by maverickg** [comment]
close via 213c819d75a3d2f6002692385c37e1f162fd4a0a

**Comment by JohnReid** [comment]
Thanks for this and the other fix.
