### ISSUE TITLE
Assignment by <- is deprecated

### ISSUE THREAD

**Issue by williamsmj** [maverickg/stan.vim#5]
`stan.vim` highlights the `=` symbol in an angry-looking color when it's used as an assignment operator, presumably to indicate that it was once an error.

But as of [stan 2.10](https://github.com/stan-dev/stan/releases/tag/v2.10.0),  `=` is the preferred assignment operator, and the `<-` assignment operator is deprecated.

Could `stan.vim` highlighting of `=` be toned down or eliminated?

**Comment by maverickg** [comment]
this is fixed with 46e8a079427ae2e3630a5459aaaf23b4e93c9603.
